# Generated by Django 3.1.1 on 2021-03-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
